print('hello world')
print('Hassan Ashraf')
print('1,2,3')
print('Hello')
print('world')
print('Hello world')
print('apple, banana, cherry')
print('1_2_3')
print('Hello World')
print('12')
print("Hello!")
print("Hassan", "Ashraf")